### ISSUE TITLE
XLNet produces incorrect output dimensions when there are consecutive X tokens

### ISSUE THREAD

**Issue by konstin** [agemagician/ProtTrans#10]
This issue originated in bio_embeddings (https://github.com/sacdallago/bio_embeddings/issues/63). To check, I've followed https://github.com/agemagician/ProtTrans/blob/master/Embedding/PyTorch/Basic/ProtXLNet.ipynb, except that I replaced the sequences with `sequences_Example = ["A E T C Z A O","S K T Z P", "M L I X X X I E P"]`. This results in the last input having an output dimension of 0 by 1024:

```python
for feature in features:
     print(feature.shape)
```

```
(7, 1024)
(5, 1024)
(0, 1024)
```

In bio_embeddings, we currently have the following code:

```python
        # tokenize sequence
        tokenized_sequence = torch.tensor(
            [self._tokenizer.encode(sequence, add_special_tokens=True)]
        ).to(self._device)
        with torch.no_grad():
            embedding = self._model(tokenized_sequence)
            # drop batch dimension and remove special tokens added to end
            embedding = embedding[0].squeeze()[:-2]
```

This generates an embeddings dimension greater than zero, however all consecutive X get treated as a single one (i.e. to the example sequence we get a shape with 7 instead of 9)

**Comment by agemagician** [comment]
Thanks for reporting the issue.

You can fix it by replacing `X` with `<unk>`, because both `X` and `<unk>` will be encoded as `0`:

```
sequences_Example = ["M L I U Z O B I E P"]
sequences_Example = [re.sub(r"[UZOB]", "<unk>", sequence) for sequence in sequences_Example]
ids = tokenizer.batch_encode_plus(sequences_Example, add_special_tokens=True, padding=True)
{'input_ids': [[34, 17, 26, 0, 0, 0, 0, 26, 21, 27, 4, 3]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}
```

I have update the examples to address this issue.

**Comment by konstin** [comment]
Thank you!
