### ISSUE TITLE
can't set attribute

### ISSUE THREAD

**Issue by skr3178** [agemagician/ProtTrans#102]
file : ProtBert_BFD_FineTune_Loc.ipynb running on colab. 
Many packages won't install due to error and therefore I have modified accordingly.

```
"""
Main training routine specific for this project
:param hparams:
"""
seed_everything(hparams.seed)

# ------------------------
# 1 INIT LIGHTNING MODEL
# ------------------------
model = ProtBertBFDClassifier(hparams)

# ------------------------
# 2 INIT EARLY STOPPING
# ------------------------
early_stop_callback = EarlyStopping(
    monitor=hparams.monitor,
    min_delta=0.0,
    patience=hparams.patience,
    verbose=True,
    mode=hparams.metric_mode,
)

# --------------------------------
# 3 INIT MODEL CHECKPOINT CALLBACK
# -------------------------------
ckpt_path = os.path.join(
    logger.save_dir,
    logger.name,
    f"version_{logger.version}",
    "checkpoints",
)
# initialize Model Checkpoint Saver
checkpoint_callback = ModelCheckpoint(
    filepath=ckpt_path + "/" + "{epoch}-{val_loss:.2f}-{val_acc:.2f}",
    save_top_k=hparams.save_top_k,
    verbose=True,
    monitor=hparams.monitor,
    period=1,
    mode=hparams.metric_mode,
)

# ------------------------
# 4 INIT TRAINER
# ------------------------
trainer = Trainer(
    gpus=hparams.gpus,
    tpu_cores=hparams.tpu_cores,
    logger=logger,
    early_stop_callback=early_stop_callback,
    distributed_backend="dp",
    max_epochs=hparams.max_epochs,
    min_epochs=hparams.min_epochs,
    accumulate_grad_batches=hparams.accumulate_grad_batches,
    val_percent_check=hparams.val_percent_check,
    checkpoint_callback = checkpoint_callback,
    precision=hparams.precision,
    amp_level=hparams.amp_level,
    deterministic=True
)
```

INFO:lightning_fabric.utilities.seed:Global seed set to 43
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-31-9d8bdf50040c>](https://localhost:8080/#) in <module>
      8 # 1 INIT LIGHTNING MODEL
      9 # ------------------------
---> 10 model = ProtBertBFDClassifier(hparams)
     11 
     12 # ------------------------

1 frames
[<ipython-input-28-9cf4e1886a37>](https://localhost:8080/#) in __init__(self, hparams)
     10     def __init__(self, hparams) -> None:
     11         super(ProtBertBFDClassifier, self).__init__()
---> 12         self.hparams = hparams
     13         self.batch_size = self.hparams.batch_size
     14 

[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __setattr__(self, name, value)
   1315                     buffers[name] = value
   1316                 else:
-> 1317                     super().__setattr__(name, value)
   1318 
   1319     def __delattr__(self, name):

AttributeError: can't set attribute

**Comment by mheinzinger** [comment]
Hm, maybe try downgrading your Pytorch lightning version? --> https://stackoverflow.com/questions/71584409/pytorch-attributeerror-cant-set-attribute

**Comment by skr3178** [comment]
I was able to fix that using the recommendation.
