### ISSUE TITLE
1D amino acid sequence generation from encoder output

### ISSUE THREAD

**Issue by bg-uni** [agemagician/ProtTrans#105]
Hello,
I have a question.

Is there a way to generate a 1D amino acid sequence from embedding obtained from last_hidden_state in T5EncoderModel?

Thanks for your help!

**Comment by mheinzinger** [comment]
No, there is no direct way to do so. However, it should be relatively easy to add such a module.
I think you should be able to recycle most of the code given in the [huggingface-examples](https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling) and replace the BERT/Encoder-models of the examples with the T5EncoderModel. You might also need to adjust the mask token (T5 only has those span tokens, e.g. <extra_id_0> etc., not the traditional <mask> tokens but probably you could also simply recycle one of the span-tokens).
This is something that we wanted to look into as well but did not find time for; it would be great if you  could share whether your experiments are successful if you proceed in this direction :)
