### ISSUE TITLE
Can we use ProtBert to fine-tune masking language model? (inquiry to memory friendly pretrained model)

### ISSUE THREAD

**Issue by gundalav** [agemagician/ProtTrans#112]
Dear Sir @mheinzinger 
(cc @agemagician)

I hope this message finds you well. I am writing to you as a follow-up to our previous [correspondence](https://github.com/agemagician/ProtTrans/issues/111). I appreciate the guidance you have provided thus far, and I have made progress in my project thanks to your assistance.

I have successfully implemented the code below, using `Rostlab/prot_t5_xl_uniref50` as the pre-trained dataset. It seems to work well, with the exception of a mind-boggling issue related to the large GPU memory requirement. Currently, it only works with AWS p3dn.24xlarge instance 32GB GPU. That is too expensive for us to use.

```
# %% Various Imports
from datasets import Dataset
from typing import Tuple
import json
import numpy as np
import random

from transformers import (
    T5Tokenizer,
    T5ForConditionalGeneration,
    T5Config,
    TrainingArguments,
    Trainer,
)


# %% Data initialization and dataset splitting into train, validation and testing.
# Base Pre-trained model
PRETRAINED_MODEL_NAME = "Rostlab/prot_t5_xl_uniref50"

# Specific for the task
FINE_TUNE_DATASET = "./dataset/random_small.txt" # can be obtained from https://pastebin.pl/view/raw/a4ac9f29

FINE_TUNED_MODEL_NAME = "prot_t5-random-small"
CONFIG_FILE = f"./prot_t5-fine-tuned-models/{FINE_TUNED_MODEL_NAME}/config"
FINE_TUNED_MODEL_FILE = f"./prot_t5-fine-tuned-models/{FINE_TUNED_MODEL_NAME}/models"


def create_dataset_object(
    file_path: str, train_ratio: float, validate_ratio: float, test_ratio: float
):
    if not (0.999 <= train_ratio + validate_ratio + test_ratio <= 1.001):
        raise ValueError(
            "The sum of train_ratio, validate_ratio, and test_ratio must be equal to 1."
        )

    with open(file_path, "r") as f:
        data = [line.strip() for line in f.readlines()]

    random.shuffle(data)

    input_texts, target_texts = [], []
    for line in data:
        input_text, target_text = line.split(" : ", 1)
        input_texts.append(input_text)
        target_texts.append(target_text)

    total_samples = len(input_texts)
    train_samples = int(total_samples * train_ratio)
    validate_samples = int(total_samples * validate_ratio)
    test_samples = int(total_samples * test_ratio)

    train_data = Dataset.from_dict(
        {
            "input_text": input_texts[:train_samples],
            "target_text": target_texts[:train_samples],
        }
    )
    validate_data = Dataset.from_dict(
        {
            "input_text": input_texts[train_samples : train_samples + validate_samples],
            "target_text": target_texts[
                train_samples : train_samples + validate_samples
            ],
        }
    )
    test_data = Dataset.from_dict(
        {
            "input_text": input_texts[
                train_samples
                + validate_samples : train_samples
                + validate_samples
                + test_samples
            ],
            "target_text": target_texts[
                train_samples
                + validate_samples : train_samples
                + validate_samples
                + test_samples
            ],
        }
    )

    return train_data, validate_data, test_data


train_ratio = 0.7
validate_ratio = 0.2
test_ratio = 0.1

train_dataset, validate_dataset, test_dataset = create_dataset_object(
    FINE_TUNE_DATASET, train_ratio, validate_ratio, test_ratio
)


# %% Tokenize and  Config
tokenizer = T5Tokenizer.from_pretrained(PRETRAINED_MODEL_NAME)


def tokenize_function(examples):
    input_ids = tokenizer(
        examples["input_text"], return_tensors="pt", padding=True, truncation=True
    ).input_ids
    decoder_input_ids = tokenizer(
        examples["target_text"], return_tensors="pt", padding=True, truncation=True
    ).input_ids
    labels = decoder_input_ids.clone()

    # T5 uses the pad_token_id as the labels to not compute the loss for the token
    labels[decoder_input_ids == tokenizer.pad_token_id] = -100

    return {
        "input_ids": input_ids,
        "labels": labels,
        "decoder_input_ids": decoder_input_ids,
    }


tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
tokenized_validate_dataset = validate_dataset.map(tokenize_function, batched=True)
tokenized_test_dataset = test_dataset.map(tokenize_function, batched=True)

config = T5Config.from_pretrained(PRETRAINED_MODEL_NAME)
config.save_pretrained(CONFIG_FILE)

print("Completed saving CONFIG")

# %% Training and Fine-Tune
model = T5ForConditionalGeneration.from_pretrained(PRETRAINED_MODEL_NAME, config=config)
training_args = TrainingArguments(
    output_dir=FINE_TUNED_MODEL_FILE,
    logging_dir="./logs",
    num_train_epochs=10,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-5,  # Change learning rate
    weight_decay=0.01,  # Add weight decay for regularization
    save_total_limit=2,  # Set the maximum number of checkpoints to keep
    gradient_accumulation_steps=4,  # Enable gradient accumulation
    fp16=True,  # Enable mixed precision training
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_validate_dataset,
)

trainer.train()
trainer.save_model(FINE_TUNED_MODEL_FILE)

# %% Evaluate the model using the test dataset, based on Cross Entropy
test_results = trainer.evaluate(eval_dataset=tokenized_test_dataset)
print("Test results:", test_results)

# Save test_results to a JSON file
with open(f"{FINE_TUNED_MODEL_FILE}/test_results.json", "w") as f:
    json.dump(test_results, f, indent=4)

print("EVAL HERE")
model.eval()
print("END EVAL HERE")

# %% Predict new data
# Load the saved model
saved_model = T5ForConditionalGeneration.from_pretrained(FINE_TUNED_MODEL_FILE)

# Calculate how many billion parameter after fine-tuning
model_parameters = filter(lambda p: p.requires_grad, saved_model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])
print(f"Number of parameters in fine-tuned model: {params/1e9} billion")


def generate_text(
    input_text: str, temperature=1.0, num_beams=1, num_return_sequences=1
):
    num_sentinels = input_text.count("<extra_id_")
    input_ids = tokenizer.encode(input_text, return_tensors="pt")

    if num_beams > 1:
        output = saved_model.generate(
            input_ids,
            max_length=input_ids.shape[1] + num_sentinels,
            num_return_sequences=num_return_sequences,
            num_beams=num_beams,
            early_stopping=True,
        )
    else:
        output = saved_model.generate(
            input_ids,
            max_length=input_ids.shape[1] + num_sentinels,
            num_return_sequences=num_return_sequences,
            do_sample=True,
            top_k=0,
            temperature=temperature,
        )

    decoded_output = [tokenizer.decode(o) for o in output]
    return decoded_output


# Test the modified function with different parameters
new_data = "N Y <extra_id_0> N M G R K Q P <extra_id_1> H <extra_id_2> L P E V C V E N Y H Y <extra_id_3> R Y P <extra_id_4> V"
print("Output with default parameters:", generate_text(new_data))
print("Output with temperature 0.7:", generate_text(new_data, temperature=0.7))
print(
    "Output with num_beams=2:",
    generate_text(new_data, num_beams=2, num_return_sequences=2),
)
```

Just a reminder, the primary goal of this task is fine-tuning the model based on the following format:

```
P R T <extra_id_0> I N S E Q W <extra_id_1> E N C E :  <s> <extra_id_0> K <extra_id_1> H <\s>
```

Given the aforementioned GPU memory concern, I am considering using [ProtBert ](https://huggingface.co/Rostlab/prot_bert)to complete the task. Would you kindly advise me on the feasibility of this approach? Moreover, could you provide any guidance on the proper format to use with ProtBert?

I tried the above code with this parameter, but failed to work:

```
PRETRAINED_MODEL_NAME = "Rostlab/prot_bert"
```

Once again, I am grateful for your invaluable support and expertise. I eagerly await your response and any insights you may offer.

Sincerely, 
G.V.

PS 1: The above code is modeled according to[ my code for basic natural MLM tasks based on T5.](https://bitbucket.org/gundalav/t5_mlm_finetune/src/master/)

PS 2: I can use the approach you [suggested](https://github.com/huggingface/transformers/tree/main/examples/flax/language-modeling#t5-like-span-masked-language-modeling) without a problem. But I prefer to rewrite the code for my better understanding and control to the process.

**Comment by mheinzinger** [comment]
Hey, 
great to hear that you got the T5 fine-tuning to work.
Regarding the change to ProtBERT: not sure whether you already did (probably you did) but you would need to modify all the imports as well. So all the T5-specific imports (config, tokenizer etc) would need to be adjusted to work. Probably you also need to adjust some other parts of your snippet but I think here is a good tutorial which shows you how to train BERT on masked language modeling (this is what you have in mind, if I'm not mistaken): [pytorch-mlm-tutorial](https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling#robertabertdistilbert-and-masked-language-modeling) 

That being said: I think there are ways to fine-tune ProtT5 also on GPUs with less vRAM. For this, you would need to install deepspeed. You can also use gradient accumulation or gradient checkpointing. You can also limit vRAM consumption by limiting sequence length. I usually start with L=256 and then fine-tune from there and only increase sequence length for the last steps. Obviously, batch-size should be 1 if you have memory problems but I guess you already set this. This huggingface-tutorial I found extremely useful to get an overview of the knobs you can turn without  much effort: https://huggingface.co/blog/accelerate-deepspeed

**Comment by gundalav** [comment]
Dear @mheinzinger 


Deepspeed works like charm! I modified my code with these training arguments:

```
training_args = TrainingArguments(
    output_dir=FINE_TUNED_MODEL_FILE,
    logging_dir="./logs",
    num_train_epochs=5,  # Reduce the number of epochs to prevent overfitting
    per_device_train_batch_size=1,  # Reduce the batch size to lower memory usage
    per_device_eval_batch_size=1,  # Reduce the batch size to lower memory usage
    save_strategy="steps",
    save_steps=314,
    save_total_limit=1,
    evaluation_strategy="steps",
    eval_steps=314,
    learning_rate=1e-4,  # Use a slightly smaller learning rate
    weight_decay=0.005,  # Reduce weight decay for less regularization
    gradient_accumulation_steps=8,  # Increase gradient accumulation steps to simulate a larger batch size without increasing memory usage
    fp16=True,
    deepspeed="ds_config.json",  # Add this line to use the DeepSpeed configuration
)
```

And with this `ds_config.json`:

```
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 32,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto"
}
```

Then execute my code with tis command:

```
$ deepspeed mycode.py
```

Voila!!! It works without any errors!

I have a question regarding the use of the completed fine-tuned model. 
Given this input:


```
new_data = "N Y <extra_id_0> N M G R K Q P <extra_id_1> H <extra_id_2> L P E V C V E N Y H Y <extra_id_3> R Y P <extra_id_4> V"
```

My function from my initial code above `generate_text(new_data)`  gives this:


```
['<pad><unk><extra_id_4><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>']
```

What are the strategies to avoid such result?

G.V.

**Comment by mheinzinger** [comment]
Great to hear that Deepspeed solved your issue.

> What are the strategies to avoid such result?

I guess there is a more fundamental problem if this happens. In such cases, I usually start to print token-IDs right before they go into the model and right afterwards to triple check that what is given to the model fits your expectation.
From a quick glance at the example you gave above (P R T <extra_id_0> I N S E Q W <extra_id_1> E N C E :  <s> <extra_id_0> K <extra_id_0> H <\s>), I think there is either a type or a general mistake in your data format as it should read: P R T <extra_id_0> I N S E Q W <extra_id_1> E N C E :  <s> <extra_id_0> K <extra_id_**_1_**> H <\s>

**Comment by gundalav** [comment]
@mheinzinger Thank you for your reply.

 I have thoroughly considered your recommendations and have made the necessary amendments.

Upon revisiting my initial post, I realized that it was just my typographical error in the input. The corrected version is as follows: `P R T <extra_id_0> I N S E Q W <extra_id_1> E N C E : <s> <extra_id_0> K <extra_id_1> H <\s>`. My actual training data can be found at this link: https://pastebin.pl/view/raw/a4ac9f29. I believe it adheres to the formatting you proposed.

Furthermore, I have confirmed that the tokenization process is accurate prior to the model prediction. I utilized the following code to validate this:


```
sample_input = "N Y <extra_id_0> N M G R K Q P <extra_id_1> H <extra_id_2> L P E V C V E N Y H Y <extra_id_3> R Y P <extra_id_4> V"
encoded_input = tokenizer.encode(sample_input, return_tensors="pt")
decoded_input = tokenizer.decode(encoded_input[0])
print("Original input:", sample_input)
print("Decoded input:", decoded_input)
```

The output generated is as follows:

```
Original input: N Y <extra_id_0> N M G R K Q P <extra_id_1> H <extra_id_2> L P E V C V E N Y H Y <extra_id_3> R Y P <extra_id_4> V
Decoded input: N Y<extra_id_0> N M G R K Q P<extra_id_1> H<extra_id_2> L P E V C V E N Y H Y<extra_id_3> R Y P<extra_id_4> V</s>
```

Considering the above, I would like to inquire if the following factors might be contributing to the issue:

The hyperparameter tuning, as specified in the TrainingArguments() function.
A relatively small training dataset, consisting of 10,000 rows of data (70% training, 20% validation, and 10% testing) used for fine-tuning.

Lastly, I would appreciate it if you could elaborate on your statement: "I usually start to print token-IDs right before they go into the model and right afterward to triple check that what is given to the model fits your expectation." Your clarification will help me better understand and apply your guidance.

Thank you once again for your invaluable assistance. I look forward to hearing from you soon.

Warm regards,

G.V.

**Comment by mheinzinger** [comment]
> Lastly, I would appreciate it if you could elaborate on your statement: "I usually start to print token-IDs right before they go into the model and right afterward to triple check that what is given to the model fits your expectation." Your clarification will help me better understand and apply your guidance.

With this statement I was referring to potential other modifications that might happen in the dataloading process. Though, your approach most likely gives exactly the same result, I usually try to be as close to actual training as possible. So I would just try to weave in the print statements you have above in your training loop, i.e., print the sample_input right before you pass it to the model. The same logic applies to the target_ids (print them as well).
I would also consider lowering the learning rate even further to 1e-5 or even 1e-6. You might also want to activate dropout given the small amount of samples you have.
Maybe also check this post on tips regarding fine-tuning of T5: https://discuss.huggingface.co/t/t5-finetuning-tips/684

**Comment by gundalav** [comment]
@mheinzinger,

I sincerely appreciate all the valuable advice you have provided me with so far. Thank you.
I was wondering if there is a smaller version of `Rostlab/prot_t5_xl_uniref50` that I can use for faster debugging of my code?

I have looked at `Rostlab/prot_t5_xl_half_uniref50-enc` and `Rostlab/prot_t5_base_mt_uniref50`, but it seems they use a different architecture, which may not be suitable for my needs.

G.V.

**Comment by mheinzinger** [comment]
Sorry, there is no smaller version of ProtT5. `Rostlab/prot_t5_xl_half_uniref50-enc` is good for prediction tasks such as secondary structure because there you only need the encoder part (-enc) of T5. But you also want the decoder for generation so this model is not suitable for your task, sorry. What you could consider is trying to load the model in half-precision '.half()' but I would be careful as this adds yet another dimension of potential failure. The 'Rostlab/prot_t5_base_mt_uniref50' model was finetuned on a downstream task but we never actually used it because it did not perform well, so I would not recommend to use it.

**Comment by BSharmi** [comment]
I think I know the problem with unk tokens, I noticed the same thing in my pre-process function. I split the sequence by 
`" ".join(sequece)` and then tokenized and checked that the `input_ids` were as expected

**Comment by gundalav** [comment]
> I think I know the problem with unk tokens, I noticed the same thing in my pre-process function. I split the sequence by
> `" ".join(sequece)` and then tokenized and checked that the `input_ids` were as expected

@BSharmi Thank you for your reply. Can you be specific on how you resolve it? Perhaps with an example code?
I'd like to know at which step it's being done. Please refer to the code shown in my original post above.

Sincerely, 
G.V.

**Comment by BSharmi** [comment]
Oh I meant in your `tokenize_function` function code where you are doing 
`input_ids = tokenizer(
        examples["input_text"], return_tensors="pt", padding=True, truncation=True
    ).input_ids`

I was thinking if you need to do
`input_ids = tokenizer(
        " ".join(examples["input_text"]), return_tensors="pt", padding=True, truncation=True
    ).input_ids`

May be not since your input output looks fine and you may have solved the problem (I cannot see your project link probably it is private). 

I also had a question, did you use a preprocessing to modify the span length and add the extra_ids? I did not see any code on how you masked your tokens.

**Comment by gundalav** [comment]
> Oh I meant in your `tokenize_function` function code where you are doing `input_ids = tokenizer( examples["input_text"], return_tensors="pt", padding=True, truncation=True ).input_ids`
> 
> I was thinking if you need to do `input_ids = tokenizer( " ".join(examples["input_text"]), return_tensors="pt", padding=True, truncation=True ).input_ids`
> 
> May be not since your input output looks fine and you may have solved the problem (I cannot see your project link probably it is private).
> 
> I also had a question, did you use a preprocessing to modify the span length and add the extra_ids? I did not see any code on how you masked your tokens.

@BSharmi Thanks for your comment. 

My `random_small.txt` dataset used in my initial code above looks like this:

```
P W G F P N V Q <extra_id_0> Q : <s> <extra_id_0> I </s>
F R A D <extra_id_0> G W F Y K C W S Q F L I D Y K E A S Y W P L C G : <s> <extra_id_0> S </s>
M Y K G S Y L D V E Y H <extra_id_0> M : <s> <extra_id_0> M </s>
```

G.V.

**Comment by BSharmi** [comment]
Gotcha!
Yes I was referring to your preprocessing code (the separate code you mentioned) and would be great if I could take a look if you don't mind. I am following https://github.com/huggingface/transformers/blob/main/examples/flax/language-modeling/run_t5_mlm_flax.py#L232 and working on the dataset class now but I don't want to use flax.

**Comment by BSharmi** [comment]
Yes! I have already butchered the flax datacollator :D On May 9, 2023, at 3:00 AM, Michael Heinzinger ***@***.***> wrote:﻿
Side-note, if you don't want to use flax, you can just extract the dataloader from the flax-script and butcher it together with the translation example (which also supports T5): https://github.com/huggingface/transformers/tree/main/examples/pytorch/translation

**Comment by BSharmi** [comment]
BTW is https://github.com/huggingface/transformers/blob/main/examples/flax/language-modeling/run_t5_mlm_flax.py#L685
trying to do a padding? If it is seems a really convoluted way to padding to the max length. Why cant we just have batch encoding instead?

**Comment by mheinzinger** [comment]
Nope, this is not adding padding but instead concatenates all text samples (or proteins) and then splits them based on the max-length (or rather: the extended max length which depends on the span-length) paramter. This makes probably sense for NLP as you tend to process consecutive, long documents but makes unfortunately less sense for proteins.
Nevertheless, I can tell you from experience that the concatenation still works ;)
Counter-intuitive, yes.
Probably not optimal, yes.
But it seems to work as the model simply learns to only attend to tokens not seperated by the special token added to the end of each sequence (this already happened before: https://github.com/huggingface/transformers/blob/main/examples/flax/language-modeling/run_t5_mlm_flax.py#L664
Why did I not change it? - From my understanding, this would have required significant code changes as you have to modify the loss, pass the attention-mask etc.. All doable but I had little experience with flax and ran out of time so I simply tried it with the concatenation and it worked out-of-the-box.
By now there is also [nanoT5](https://github.com/PiotrNawrot/nanoT5). I did not specifically check but maybe the allow padding during pre-training. Maybe worth checking.
In case you find sth, it would be great if you could share this information here :)
Good luck!

**Comment by BSharmi** [comment]
Thank you for explaining in such detail!
Nor sure why would I have to modify loss? It would still be cross entropy right?
The concatenation still does not make sense to me because 
`concatenated_examples = {k: list(chain(*examples[k])) for k in examples.keys()}`
`examples` has `input_text`, `input_ids` as keys and all of them are concatenated right?

**Comment by mheinzinger** [comment]
Yup, you still use cross entropy but you would have to handle padded elements accordingly.

**Comment by BSharmi** [comment]
Actually ignore my question I figured it out and have a new issue opened so that I don't crash this thread!

**Comment by mheinzinger** [comment]
In case it should still be relevant, we now have a finetuning script using LoRA layers: https://github.com/agemagician/ProtTrans/tree/master/Fine-Tuning

**Comment by BSharmi** [comment]
Hi @gundalav do you mind sharing your pre-training code (https://bitbucket.org/gundalav/t5_mlm_finetune/src/master/)? I have my training code based on this thread and want to check if I missed anything. It would really help me train my model.

Thank you very much!

**Comment by mheinzinger** [comment]
Update: https://github.com/agemagician/ProtTrans/issues/137#issuecomment-1817576165
