### ISSUE TITLE
Predicting protein distance map

### ISSUE THREAD

**Issue by akirasosa** [agemagician/ProtTrans#12]
Hi,

It's just a notice.
I have just tried ProtBert to predict protein distance map. It works pretty well.
https://github.com/akirasosa/bert-fold

Thanks for the repo!

**Comment by agemagician** [comment]
Thanks @akirasosa for sharing your use-case.
It make us feel happy to see our models are being used for various downstream tasks, especially an important downstream task such as structure prediction.

I have created new label called "community use-case" so others can find such use-cases easily.

I would recommend the following updates in your work:
1. ProtBert model is 30 layers not 16 layers as mentioned in your blog post.
2. ProtBert model is our 3rd best model. You should try ProtBert-BFD which is trained on more than 2 billion sequences.
3. More details about the fine-tuning process, did you fine-tune the whole model or only the last layer.
4. What kind of new layers you added on top of ProtBert for this task ?
5. What are other standard metrics for this task that you could integrate ?

**Comment by akirasosa** [comment]
@agemagician Thanks for the comprehensive advises. It's really helpful.

> ProtBert model is 30 layers not 16 layers as mentioned in your blog post.
Sorry. I updated it.

> ProtBert model is our 3rd best model. You should try ProtBert-BFD which is trained on more than 2 billion sequences.
I will try it.

> More details about the fine-tuning process, did you fine-tune the whole model or only the last layer.
Whole model.

> What kind of new layers you added on top of ProtBert for this task ?
This one to get pairwise predictions.
https://github.com/akirasosa/bert-fold/blob/master/src/bert_fold/modules/pairwise_distance_decoder.py#L11

> What are other standard metrics for this task that you could integrate ?
I have tried Top L/5 Precision, but still I don't figure out how it can be applied in some edge cases...
https://github.com/akirasosa/bert-fold/blob/master/src/bert_fold/metrics.py#L58

> Use full-precision with gradient checkpoint. You only need to send "gradient_checkpointing=True" to model initialisation.
I will try it.

> Use Casp13 dataset and compare the results with AlphaFold.
Yes. I'm also trying similar feature engineering with AlphaFold. CASP14 will end soon. Its result would be interesting too.
