### ISSUE TITLE
OSError: Can't load tokenizer for 'Rostlab/prot_t5_xl_uniref50'

### ISSUE THREAD

**Issue by moonhuwaa** [agemagician/ProtTrans#121]
Dear Sir,
I have the following code:

`
def get_embedding(sequences_Example):

    tokenizer = T5Tokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50", do_lower_case=False)
    model = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_uniref50")
    gc.collect()
    print(torch.cuda.is_available())
    # 'cuda:0' if torch.cuda.is_available() else
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    model = model.eval()`

When I tried to use this pre trained model, the following error occurred, but I don't know where it went wrong. Here is the error message.
`
Traceback (most recent call last):

  File "pu_learning.py", line 33, in <module>
    P = get_embedding(tail_seq)  # only tail
  File "/root/nas-private/embedding.py", line 12, in get_embedding
    tokenizer = T5Tokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50", do_lower_case=False)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1809, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'Rostlab/prot_t5_xl_uniref50'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'Rostlab/prot_t5_xl_uniref50' is the correct path to a directory containing all relevant files for a T5Tokenizer tokenizer.`

This is the version number of the relevant library.
transformers: 4.30.2
SentencePiece: 0.1.99

I really want to know where the problem is and how to modify it.
Thanks and hope to hear from you.
Moonhuwaa

**Comment by mheinzinger** [comment]
Hi @moonhuwaa , 
unfortunately, I can not reproduce your problem. The code to load the tokenizer you posted above works fine on my end. I am using transformers 4.29 and sentencepiece 0.1.97 . However, I do not think that the versions are actually the problem here. Did you check whether you might have a directory in the same folder which has a conflicting name?

**Comment by ColaZHZ** [comment]
I have the same problem. How did you solve it？
