### ISSUE TITLE
Availability of Seq2Seq Autoencoder Models for Protein Sequences

### ISSUE THREAD

**Issue by khokao** [agemagician/ProtTrans#122]
Hi, thanks for your great work!

Are there any models provided in this repository that can be used as a sequence-to-sequence autoencoder?

More specifically, my interest lies in extracting features from protein sequences and then reconstructing the protein sequences from those extracted features.

**Comment by mheinzinger** [comment]
We have no such model that would do the job out-of-the-box. 
What you could do is: extract features using e.g. the encoder-side of ProtT5, get a compressed version thereof (either average pooling over length-dimension or learnt auto-encoder compression e.g. via attention-pooling) and then reconstruct the original sequence from there using a decoder model (maybe recycle existing ProtGPT2: https://huggingface.co/nferruz/ProtGPT2 )

**Comment by khokao** [comment]
I see. Thank you very much for the swift reply!
