### ISSUE TITLE
New364 dataset

### ISSUE THREAD

**Issue by SamarthGarg09** [agemagician/ProtTrans#125]
Can we get the link to the new364 dataset?

**Comment by mheinzinger** [comment]
Sure, good point, I always wanted to add them but this kept slipping through.
Here are the datasets that we used for ProtTrans evaluation (my colleague @t03i kindly prepared this a while ago): https://drive.google.com/drive/folders/1URNE5gaUzVylvj0-jk0lq4kX7msIwM80?usp=drive_link
