### ISSUE TITLE
Gene Ontology (GO) prediction

### ISSUE THREAD

**Issue by JNU-luyi** [agemagician/ProtTrans#126]
Hello, can this embedding be used to predict protein functions, such as Gene Ontology (GO) prediction? Is there any relevant case for reference?

**Comment by JNU-luyi** [comment]
Ok, thank you for your reply. Now I am a beginner in this field. Are you an expert in protein function prediction (GO)? I just started this research recently and have no ideas. I would like to know what is the mainstream method of deep learning in this topic, or do you have any relevant papers to recommend



---- Replied Message ----
| From | Michael ***@***.***> |
| Date | 08/17/2023 15:56 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [agemagician/ProtTrans] Gene Ontology (GO) prediction (Issue #126) |

Hi, yes, there is already some work on our end on this: https://github.com/Rostlab/goPredSim
Essentially, you just compute euclidean distance between a set of embedded proteins with GO annotations and a set of embedded proteins without annotation and then you simply copy&paste the annotation of the closest hit and consider this a prediction. This worked remarkably well for CAFA4.

**Comment by mheinzinger** [comment]
I think the best way to get started is to get an overview of methods that competed in CAFA3: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1835-8
 
There is also a good overview provided by the most recent CAFA5: https://www.kaggle.com/competitions/cafa-5-protein-function-prediction
