### ISSUE TITLE
Improvements on Quick Start in README

### ISSUE THREAD

**Issue by delta2323** [agemagician/ProtTrans#127]
When I ran the quick start in `README`, I found that I needed to modify the code to make it runnable.

- `T5Tokenizer` does not have the `to` method
- 're' package should be installed
- Fix several typos (`sequence_examples`, `embedding_repr`)

Also, `PretrainedTokenizer.batch_encode_plus` is obsolete, at least from Jul. 2020: [Document](https://huggingface.co/docs/transformers/v4.32.0/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.batch_encode_plus), [PR](https://github.com/huggingface/transformers/pull/6110/files#diff-85b29486a884f445b1014a26fecfb189141f2e6b09f4ae701ee758a754fddcc1R2069)

Considering the above, I think the following changes to the quick start are preferable: https://github.com/delta2323/ProtTrans/commit/afa87dcea4fe59873f69945d0ec1a72f401ac8cd

I appreciate the team's work. I hope this comment may help to improve the package.

**Comment by mheinzinger** [comment]
All valid points, thanks for raising! - I've merged your suggestions :)
If you should find anything else unclear or have suggestions for improvement, please let me know.
