### ISSUE TITLE
Fine-tuning smaller models in half-precision

### ISSUE THREAD

**Issue by pawel-rezo** [agemagician/ProtTrans#135]
Fine-tuning with ProtT5 large encoder (`model = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_uniref50")`) requires 20Gb+ of GPU memory and is computationally expensive. Is there a way of running a model in half-precision or using a smaller encoder?

If I want to check the list of available T5 encoders, how can I do it?

**Comment by pawel-rezo** [comment]
I solved the first part with the code:
```
    if half_precision:
        model = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_uniref50")
        tokenizer = T5Tokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50")
    elif half_precision and torch.cuda.is_available() : 
        tokenizer = T5Tokenizer.from_pretrained('Rostlab/prot_t5_xl_half_uniref50-enc', do_lower_case=False)
        model = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_half_uniref50-enc", torch_dtype=torch.float16).to(device)
    else:
      raise ValueError('Half precision can be run on GPU only.')
```

It'd still be nice to learn about the namespace of models that we use in `ProtTrans`.

**Comment by RSchmirler** [comment]
@pawel-rezo  
Yes exactly, thanks for that!
You can also give ` fp16 = True` to the HF Trainer TrainingArguments but directly loading the half-precision model might be even better.
