### ISSUE TITLE
Error loading 'pytorch_lightning.metrics.sklearns'

### ISSUE THREAD

**Issue by yzhang-github-pub** [agemagician/ProtTrans#14]
ProtBert_FineTune_Loc.ipynb was run in google's colab. I got the error from the line in 4th code cell 'from pytorch_lightning.metrics.sklearns import Accuracy':  ModuleNotFoundError: No module named 'pytorch_lightning.metrics.sklearns'.

Any help is appreciated.

**Comment by agemagician** [comment]
Pytorch lighting has changed its library and that caused the Colab example to break.

All what you need to do is to change :
`!pip install -q test_tube transformers pytorch-nlp git+https://github.com/PyTorchLightning/pytorch-lightning.git`
to
`!pip install -q test_tube transformers pytorch-nlp pytorch-lightning==0.9.0`
This should fix it.

I will update the Colab example to address this issue.

**Comment by yzhang-github-pub** [comment]
Thanks! Can you also update ProtBert_FineTune_Loc.ipynb? Seems only notebook for bfd is updated.

**Comment by agemagician** [comment]
Done, please check the fine-tuning section.
