### ISSUE TITLE
DefaultCPUAllocator: not enough memory

### ISSUE THREAD

**Issue by Chokerino** [agemagician/ProtTrans#15]
hello,

i wanted to use the model to train some models but i am getting the following error 
`RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 16777216 bytes. Buy new RAM!` which is barely 16mb. The code works fine on colab but im not sure what is causing the issue. 
```
from transformers import AutoTokenizer, AutoModelWithLMHead

tokenizer = AutoTokenizer.from_pretrained("Rostlab/prot_t5_xl_bfd",cache_dir=".")

model = AutoModelWithLMHead.from_pretrained("Rostlab/prot_t5_xl_bfd",cache_dir=".")
```

**Comment by agemagician** [comment]
Hi,

Since, I don't have access to your machine, I can't reproduce your error.
However, the error simply means that you ran out of memory on your computer.

You can:
1. Try another machine.
2. Upgrade your ram.
3. Use a smaller model for example "Rostlab/prot_bert_bfd".
