### ISSUE TITLE
Question about input data for ProtBert-FineTuning-Localization.ipynb

### ISSUE THREAD

**Issue by yzhang-github-pub** [agemagician/ProtTrans#16]
I did a test run of the notebook. After input was downloaded to ./data/, I inspected the test dataset. The protein sequences seem to have been tokenized by adding a space between 2 residues. However it seems for every 70 residues, there is no space between 70th and 71st residues, as shown below where second last ones is "SL" instead of "S L":

M G L P V S W A P P A L W V L G C C A L L L S L W A L C T A C R R P E D A V A P R K R A R R Q R A R L Q G S A T A A E A S L L R R T H L C SL S ......

Why is this way?

**Comment by agemagician** [comment]
Yes, this is a mistake on the dataset. Every token should be separated by space.
That's way on "ProtBert-BFD-FineTuning-MS.ipynb" I apply this line:
`seq = " ".join("".join(self.seqs[idx].split()))`
Which make sure that there is always space between every token.

I will do the same for the PytorchLighting examples.

**Comment by agemagician** [comment]
I have add the above code on all MS and Loc notebooks.
Now, it doesn't matter if the input has space between every token or not, the code will force it.
