### ISSUE TITLE
Does prot_bert have Classifier output layer?

### ISSUE THREAD

**Issue by yzhang-github-pub** [agemagician/ProtTrans#18]
"bert-base-uncased" model output layer has pooler and classifier (from print(list(model.named_parameters())[-4:]). Seems "prot_bert" only has pooler in output layer. Just want to confirm.

**Comment by agemagician** [comment]
If you need the "seq_relationship" then you have to call the correct class either "BertForPreTraining" or "BertForNextSentencePrediction".

Please, refer to:
https://huggingface.co/transformers/model_doc/bert.html#overview

However, you have to know that we didn't train the model to learn relationship between two protein sequences during training, so the output for the "seq_relationship" might not by useful.
