### ISSUE TITLE
Model Freezing

### ISSUE THREAD

**Issue by wjs20** [agemagician/ProtTrans#19]
Hi guys 

Interested to try the model out! I'd like to try and implement some of the fastai2 library transfer learning approaches, one of which is freezing model parameters while fitting a new model head for a few cycles. You advise against doing this, can you tell me why? 

Thanks.

**Comment by agemagician** [comment]
Hi @wjs20 ,

From our expirements, we recommend two approaches:
1. Feature extraction: freeze the whole model and add different layers on top. This requires a lot of trails until you find the best model architecture you need to add on top.
2. Fine tuning: fine-tune the whole model and just add a final linear layer. You may freeze the model for some cycles but you should fine-tune it at some point during the training. This method doesn't need any model tuning, but requires higher GPU memory during the fine tuning process.

What we don't recommend:
To freeze the whole model during the whole training and only add a final linear layer. This will lead to much lower accuracy.
