### ISSUE TITLE
Will the prot_bert or prot_bert_BFD model provide classification support or any other API in the future?

### ISSUE THREAD

**Issue by shysuen** [agemagician/ProtTrans#23]
I think the pre-trained model is excellent work! 

However, fine tune the prot_bert or prot_bert_bfd model is so hard and cost a lot of time one the parameter optimization. 

So, I just want to ask if you have any plans to develop related API for protein classification questions.

**Comment by agemagician** [comment]
Hi @shysuen ,

You don't need to fine-tune the models at all, you can get the same results with feature extraction "[embedding](https://github.com/agemagician/ProtTrans/tree/master/Embedding)". Which is very fast "faster than the fastest MSA method", and have approximately the same results as fine-tuning ProtBert models. However, you need to carefully choose the architecture that you will use to make the prediction using the embedding to achieve the best performance.

Regarding [fine-tuning](https://github.com/agemagician/ProtTrans/tree/master/Fine-Tuning), we have used Google Colab Pro for fine-tuning ProtBert model for secondary structure, localization and Membrane prediction. It took approximately around 1-3 hours without any hyper-parameter feature engineering.

Regarding the API, currently one of our partners "huggingface - @patrickvonplaten @julien-c" is providing a paid API for our models' inference:
https://huggingface.co/pricing
It is great if you have a large massive dataset that you need to extract it's feature.

If you have a smaller-medium dataset, then you can use one of my colleagues "@sacdallago" API for free:
https://github.com/sacdallago/bio_embeddings

We have also discussion with our industrial partners to provide API for both inference and fine-tuning as a service for customrers.
