### ISSUE TITLE
ResourceExhaustedError : OOM when allocating tensor

### ISSUE THREAD

**Issue by Trishna-Chakraborty** [agemagician/ProtTrans#25]
I was trying to embed a protein sequence of length 35213 with prot_bert_bfd, but got 'ResourceExhaustedError: OOM when allocating tensor'. I was able to encode sequences with length less than 1000 easily. 
Currently I'm using google colab. Could you please give an estimation of GPU memory requirement to embed a sequence of length 35213? Also is there any alternative way with existing memory state - like segmenting the sequence?

**Comment by agemagician** [comment]
You have three options:
1) The only GPU that could be able to embed such length using mixed precision is NVIDIA Quadro RTX 8000 with 48 GB of memory.
2) Switch to CPU when you embed very long sequences. It will be slow, but it should be only few sequences with such length.
3) For very long sequences, use XLNet model and divide your sequences into chunks and use the memory capabilities of XLNet model:
https://github.com/agemagician/ProtTrans/blob/master/Embedding/PyTorch/Advanced/ProtXLNet.ipynb

**Comment by Trishna-Chakraborty** [comment]
Thanks a lot for always providing prompt response. I've picked your 3rd option. Could you please tell me whether I'm on right path or missing something?

sequence = "MAGSSGYGLLKLLQKLSDEEFQRFKELLREEPEKFKLKPISWTKIENSSKESLVTLLNTHYPGQAWNMMLSLFLQVNREDLSIMAQKKKRHKQTKYKKFMKTTFERIWTLETNTHIPDRNYHLIVEVQYKALQEIFDSESEPVTAIVAGTTGEGKTTFLRKAMLDWASGVLLQNRFQYVFFFSVFSLNNTTELSLAELISSTLPESSETVDDILSDPKRILFILDGFDYLKFDLELRTNLCNDWRKRLPTQIVLSSLLQKIMLPGCSLLLELGQISVPKIRHLLKYPRVITMQGFSERSVEFYCMSFFDNQRGIEVAENLRNNEVLHLCSNPYLCWMFCSCLKWQFDREEEGYFKAKTDAAFFTNFMVSAFKSTYAHSPSKQNRARLKTLCTLAVEGMWKELFVFDSEDLRRNGISESDKAVWLKMQFLQTHGNHTVFYHPTLQSYFAAMFYFLKQDKDICVPVIGSIPQLLGNMYARGQTQWLQLGTFLFGLINEQVAALLQPCFGFIQPIYVRQEIICYFKCLGQQECNEKLERSQTLFSCLRDSQEERFVRQVVDLLEEITVDISSSDVLSVTAYALQKSSKLKKLHLHIQKTVFSEIYCPDHCKTRTSIGKRRNTAEYWKTLCGIFCNLYVLDLDSCQFNKRAIQDLCNSMSPTPTVPLTAFKLQSLSCSFMADFGDGSLFHTLLQLPHLKYLNLYGTYLSMDVTEKLCAALRCSACRVEELLLGKCGISSKACGIIAISLINSKVKHLSLVENPLKNKGVMSLCEMLKDPSCVLQSLMLSYCCLTFIACGHLYEALLSNKHLSLLDLGSNFLEDTGVNLLCEALKDPNCTLKELWLPGCFLTSQCCEEISAVLICNRNLKTLKLGNNNIQDTGVRQLCEALSHPNCNLECLGLDLCEFTSDCCKDLALALTTCKTLNSLNLDWKTLDHSGLVVLCEALNHKRCNLKMLGLDKSAFSEESQTLLQDVEKKNNNLNILHHPWFEAERNKRGTRLVWNSRN"
length = 512
chunk_seq = [sequence[0+i:length+i] for i in range(0, len(sequence), length)]
processed_sequences = [" ".join(seq) for seq in chunk_seq]
processed_sequences = [re.sub(r"[UZOB]", "X", sequence) for sequence in processed_sequences]
mems = None
for seq in processed_sequences :
    ids = tokenizer.batch_encode_plus([seq], add_special_tokens=True, padding=True, return_tensors="tf")
    input_ids = ids['input_ids']
    attention_mask = ids['attention_mask']
    output = model(input_ids,attention_mask=attention_mask,mems=mems,use_mems = True)
    mems = output.mems

embedding = output.last_hidden_state

**Comment by Trishna-Chakraborty** [comment]
Thanks a lot for providing prompt response always. I've tried your 3rd option. Could you please tell me whether I'm on right path or missing something?

	sequence = "MAGSSGYGLLKLLQKLSDEEFQRFKELLREEPEKFKLKPISWTKIENSSKESLVTLLNTHYPGQAWNMMLSLFLQVNREDLSIMAQKKKRHKQTKYKKFMKTTFERIWTLETNTHIPDRNYHLIVEVQYKALQEIFDSESEPVTAIVAGTTGEGKTTFLRKAMLDWASGVLLQNRFQYVFFFSVFSLNNTTELSLAELISSTLPESSETVDDILSDPKRILFILDGFDYLKFDLELRTNLCNDWRKRLPTQIVLSSLLQKIMLPGCSLLLELGQISVPKIRHLLKYPRVITMQGFSERSVEFYCMSFFDNQRGIEVAENLRNNEVLHLCSNPYLCWMFCSCLKWQFDREEEGYFKAKTDAAFFTNFMVSAFKSTYAHSPSKQNRARLKTLCTLAVEGMWKELFVFDSEDLRRNGISESDKAVWLKMQFLQTHGNHTVFYHPTLQSYFAAMFYFLKQDKDICVPVIGSIPQLLGNMYARGQTQWLQLGTFLFGLINEQVAALLQPCFGFIQPIYVRQEIICYFKCLGQQECNEKLERSQTLFSCLRDSQEERFVRQVVDLLEEITVDISSSDVLSVTAYALQKSSKLKKLHLHIQKTVFSEIYCPDHCKTRTSIGKRRNTAEYWKTLCGIFCNLYVLDLDSCQFNKRAIQDLCNSMSPTPTVPLTAFKLQSLSCSFMADFGDGSLFHTLLQLPHLKYLNLYGTYLSMDVTEKLCAALRCSACRVEELLLGKCGISSKACGIIAISLINSKVKHLSLVENPLKNKGVMSLCEMLKDPSCVLQSLMLSYCCLTFIACGHLYEALLSNKHLSLLDLGSNFLEDTGVNLLCEALKDPNCTLKELWLPGCFLTSQCCEEISAVLICNRNLKTLKLGNNNIQDTGVRQLCEALSHPNCNLECLGLDLCEFTSDCCKDLALALTTCKTLNSLNLDWKTLDHSGLVVLCEALNHKRCNLKMLGLDKSAFSEESQTLLQDVEKKNNNLNILHHPWFEAERNKRGTRLVWNSRN"
	length = 512
	chunk_seq = [sequence[0+i:length+i] for i in range(0, len(sequence), length)]
	processed_sequences = [" ".join(seq) for seq in chunk_seq]
	processed_sequences = [re.sub(r"[UZOB]", "X", sequence) for sequence in processed_sequences]
	mems = None
	for seq in processed_sequences :
	    ids = tokenizer.batch_encode_plus([seq], add_special_tokens=True, padding=True, return_tensors="tf")
	    input_ids = ids['input_ids']
	    attention_mask = ids['attention_mask']
	    output = model(input_ids,attention_mask=attention_mask,mems=mems,use_mems = True)
	    mems = output.mems

	embedding = output.last_hidden_state

**Comment by agemagician** [comment]
The code is correct, but you should have an array or a list to concatenate/append the embedding of each chunk.
Otherwise, you will have the embedding for only your last chunk "2nd part of the sequence".

Your code should be something like:
```
mems = None
embedding = []
for seq in processed_sequences :
    ids = tokenizer.batch_encode_plus([seq], add_special_tokens=True, padding=True, return_tensors="tf")
    input_ids = ids['input_ids']
    attention_mask = ids['attention_mask']
    output = model(input_ids,attention_mask=attention_mask,mems=mems,use_mems = True)
    mems = output.mems
    embedding.append(output.last_hidden_state)
```

**Comment by Trishna-Chakraborty** [comment]
Thanks ^_^
