### ISSUE TITLE
ValueError: The first argument to `Layer.call` must always be passed.

### ISSUE THREAD

**Issue by Trishna-Chakraborty** [agemagician/ProtTrans#26]
While running ProtXLNet_TF.ipynb with your default setup, following line is causing 'ValueError: The first argument to `Layer.call` must always be passed' :
            embedding, memory = model(inputs=input_ids,attention_mask=attention_mask,mems=None)

**Comment by agemagician** [comment]
Thanks for reporting the issue.
This is due to the latest changes in hugging-face library.
I just fixed it.
