### ISSUE TITLE
paper figure6A

### ISSUE THREAD

**Issue by yuanenming** [agemagician/ProtTrans#27]
Thanks for your excellent larger-scale protein language modeling work. Figure6A in your original paper is very vivid and informative! I am just wondering would you like to share the source coder to draw Figure6A.

Thanks a lot!

**Comment by agemagician** [comment]
This figure was generated by @mheinzinger .

Could you please reply this request ?

Thanks.

**Comment by mheinzinger** [comment]
Sure, here you go (not perfectly clean but maybe a good starting point):
[tsne_aas.zip](https://github.com/agemagician/ProtTrans/files/5750658/tsne_aas.zip)
I've added a comment where you need to insert the path to your npz file which holds single amino acids IDs as keys and corresponding embeddings as vectors.

**Comment by yuanenming** [comment]
Cool!!! Thank you !
