### ISSUE TITLE
Load ProtBert or ProtBert-BFD in TensorFlow

### ISSUE THREAD

**Issue by JoeVPhillips** [agemagician/ProtTrans#3]
Hello, is it possible to load ProtBert or ProtBert-BFD using TensorFlow?

I have successfully loaded the ProtBert model in PyTorch using the following notebook:
[]((https://github.com/agemagician/ProtTrans/blob/master/Embedding/Basic/ProtBert.ipynb))

and loading from the checkpoints at the following link:
modelUrl = 'https://www.dropbox.com/s/dm3m1o0tsv9terq/pytorch_model.bin?dl=1'

But I would like to do so in TensorFlow. I have tried the following changes in the notebook provided:

1. Changing:
`model = BertModel.from_pretrained(modelFolderPath)`
to:
`model = BertModel.from_pretrained(modelFolderPath, from_tf=True)`
but this raises the error that the h5 files are not found at the above link. Is there an alternative link that would have a .h5 or .ckpt file?

2. Adding framework="tf" to the pipeline:
`model = pipeline('feature-extraction', model=model, tokenizer=tokenizer, device=-1, framework="tf")`

but this errors on the line: `embedding = model(sequences_Example)` with the following:

> ~/.../site-packages/transformers/pipelines.py in _forward(self, inputs, return_tensors)
>     499             if self.framework == "tf":
>     500                 # TODO trace model
> --> 501                 predictions = self.model(inputs.data, training=False)[0]
>     502             else:
>     503                 with torch.no_grad():
> 
> TypeError: forward() got an unexpected keyword argument 'training'

TF version: 2.1.0

Any advice would be greatly appreciated,
Joe

**Comment by agemagician** [comment]
I have add ProtBert-BFD version to the GitHub rep:
https://github.com/agemagician/ProtTrans/blob/master/Embedding/TensorFlow/Advanced/ProtBert-BFD.ipynb

I will try to add the rest of the models Tensorflow version next week.

**Comment by JoeVPhillips** [comment]
Hi,

I can't reply on the issue thread as it is closed, but just to say thank
you and this resolves my issue entirely.

Best wishes,
Joe

**Comment by flomock** [comment]
Hi,
can you please add the rest as well?
Thanks in advance. :)

**Comment by agemagician** [comment]
@flomock  We added the rest of the models.
