### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[41500,1002,1024] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:ResourceGather]

### ISSUE THREAD

**Issue by leiqichn** [agemagician/ProtTrans#30]
Dear Sir or Madam,

I ran this script(ProtTrans/Embedding/TensorFlow/Advanced/ProtBert.ipynb)  on a Linux server with 251GB of memory. 
It reported the following error：
`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[41500,1002,1024] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:ResourceGather]`

It shows out of memory. My input is 41,500 amino acid sequences of 1000 lengths. Then I tried to enter only a thousand sequences, but it still got the same error.
How can I solve this problem?

Best regards,
Lei Qi

**Comment by leiqichn** [comment]
<b>3. Create or load sequences and map rarely occured amino acids (U,Z,O,B) to (X)<b>

```
#sequences_Example = ["A E T C Z A O","S K T Z P"]

import pickle
with open('/content/sample_data/bert_sequences_Example.pkl','rb') as in_file:
  sequences_list = pickle.load(in_file)
```
My input just like the sequences_Example format.  I put in a small number of amino acid sequences and it works.  But I need word embedding for the 41500 protein sequences. How can I solve this problem?

**Comment by agemagician** [comment]
please, refer to https://github.com/agemagician/ProtTrans/issues/25

**Comment by leiqichn** [comment]
> please, refer to #25

Thank you for your answer!  But I don't think I have the same problem with him.  My protein sequence contains 1,000 amino acids.  I don't think 1000 length is very long, because it works if I input a single protein. I have 41,500 of these proteins. And It reported the error.  So how many proteins are reasonable for me to input into the model?  Could you please tell me how can I solve this problem?

**Comment by agemagician** [comment]
It depends on your GPU, you have to divide your dataset into small batches and process each batch separately.

**Comment by leiqichn** [comment]
OK. Thanks a lot for providing prompt responses always!
