### ISSUE TITLE
Truncation

### ISSUE THREAD

**Issue by udibgui** [agemagician/ProtTrans#33]
Hi, does the model have a maximum length of sequences it can take? I am wondering as protein sequences can be very long

**Comment by agemagician** [comment]
ProtBert, ProtAlbert and ProtElectra have a maximum length of 40,000. (40 thousand amino acids).

ProtTXL, ProtXLNet, and ProtT5 have no maximum length. They can process any protein length, only the CPU or the GPU will be the limit.
