### ISSUE TITLE
Add performer and reformer model

### ISSUE THREAD

**Issue by behroozazarkhalili** [agemagician/ProtTrans#35]
Could you please add the pre-trained performer and reformer models trained on protein datasets.

As you know, Performer, a Transformer architecture with attention mechanisms that scale linearly, thus enabling faster training while allowing the model to process longer lengths. Therefore, it could handle longer protein sequences.

https://ai.googleblog.com/2020/10/rethinking-attention-with-performers.html?m=1

Thanks in advance.

**Comment by agemagician** [comment]
We have our eyes on the new efficient transformer models; however, after testing these models, they either don't scale well on large-scale training, or the released script has many bugs or missing features.

We will update the repo with one of the efficient transformer models after we find a good implementation.

**Comment by behroozazarkhalili** [comment]
> We have our eyes on the new efficient transformer models; however, after testing these models, they either don't scale well on large-scale training, or the released script has many bugs or missing features.
> 
> We will update the repo with one of the efficient transformer models after we find a good implementation.

It's okay. The reason why I ask this feature is seeing the reformer implantation in some protein datasets in tensor2tensor frameworks.
