### ISSUE TITLE
A suggestion for Fine-Tuning code

### ISSUE THREAD

**Issue by medlen** [agemagician/ProtTrans#37]
In the file: ProtTrans/Fine-Tuning/ProtBert-BFD-FineTune-SS3.ipynb, there is a piece of code:

```
# Consider each label as a tag for each token
unique_tags = set(tag for doc in train_labels for tag in doc)
tag2id = {tag: id for id, tag in enumerate(unique_tags)}
id2tag = {id: tag for tag, id in tag2id.items()}
```

This code has a hidden problem: If we first run this code, we will get a  mapping from tag to id, but if we restart the kernal, and run it again, the mapping is changed! 

This caused a problem: When we first fine-tuned the model,  and then reload the model from the local to predict new sequences, the result become random, because the mapping is changed! 

I met this problem when I quoted this piece of code.

So I think it would be better to change the code, like the following:
```
unique_tags = set(tag for doc in train_labels for tag in doc)
unique_tags  = sorted(list(unique_tags))  # make the order of the labels unchanged
# or 
# unique_tags = {'B': 0, 'C': 1, 'I': 2, 'H': 3, 'G': 4, 'S': 5, 'T': 6, 'E': 7} 
tag2id = {tag: id for id, tag in enumerate(unique_tags)}
id2tag = {id: tag for tag, id in tag2id.items()}
```

**Comment by agemagician** [comment]
Hi @medlen  ,

Thanks for reporting the problem; we have integrated your suggestion into the notebook to make it deterministic :)
