### ISSUE TITLE
Mask tokens for T5 models

### ISSUE THREAD

**Issue by joshim5** [agemagician/ProtTrans#39]
Congrats on releasing the most recent T5 models! 🎉

I'm trying to tokenize sequences containing `[MASK]` tokens, but the mask_token index doesn't seem to be set with the model. To illustrate, suppose I try something like this:
```
tokenizer = ProtTransTokenizer.from_pretrained("Rostlab/prot_t5_xl_bfd")
print(tokenizer.mask_token)
```

I get the following output:
```
Using mask_token, but it is not set yet.
None
```

Printing out the tokenizer itself, I see the following output --- no extra mask tokens.

```
PreTrainedTokenizer(name_or_path='Rostlab/prot_t5_xl_bfd', vocab_size=128, model_max_len=1000000000000000019884624838656, is_fast=False, padding_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>', 'additional_special_tokens': ['<extra_id_0>', '<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>', '<extra_id_5>', '<extra_id_6>', '<extra_id_7>', '<extra_id_8>', '<extra_id_9>', '<extra_id_10>', '<extra_id_11>', '<extra_id_12>', '<extra_id_13>', '<extra_id_14>', '<extra_id_15>', '<extra_id_16>', '<extra_id_17>', '<extra_id_18>', '<extra_id_19>', '<extra_id_20>', '<extra_id_21>', '<extra_id_22>', '<extra_id_23>', '<extra_id_24>', '<extra_id_25>', '<extra_id_26>', '<extra_id_27>', '<extra_id_28>', '<extra_id_29>', '<extra_id_30>', '<extra_id_31>', '<extra_id_32>', '<extra_id_33>', '<extra_id_34>', '<extra_id_35>', '<extra_id_36>', '<extra_id_37>', '<extra_id_38>', '<extra_id_39>', '<extra_id_40>', '<extra_id_41>', '<extra_id_42>', '<extra_id_43>', '<extra_id_44>', '<extra_id_45>', '<extra_id_46>', '<extra_id_47>', '<extra_id_48>', '<extra_id_49>', '<extra_id_50>', '<extra_id_51>', '<extra_id_52>', '<extra_id_53>', '<extra_id_54>', '<extra_id_55>', '<extra_id_56>', '<extra_id_57>', '<extra_id_58>', '<extra_id_59>', '<extra_id_60>', '<extra_id_61>', '<extra_id_62>', '<extra_id_63>', '<extra_id_64>', '<extra_id_65>', '<extra_id_66>', '<extra_id_67>', '<extra_id_68>', '<extra_id_69>', '<extra_id_70>', '<extra_id_71>', '<extra_id_72>', '<extra_id_73>', '<extra_id_74>', '<extra_id_75>', '<extra_id_76>', '<extra_id_77>', '<extra_id_78>', '<extra_id_79>', '<extra_id_80>', '<extra_id_81>', '<extra_id_82>', '<extra_id_83>', '<extra_id_84>', '<extra_id_85>', '<extra_id_86>', '<extra_id_87>', '<extra_id_88>', '<extra_id_89>', '<extra_id_90>', '<extra_id_91>', '<extra_id_92>', '<extra_id_93>', '<extra_id_94>', '<extra_id_95>', '<extra_id_96>', '<extra_id_97>', '<extra_id_98>', '<extra_id_99>']})
```

We're trying to get the best possible performance with your models, so it's important to use the same mask token that was used during pre-training. [The index for this model](https://huggingface.co/Rostlab/prot_t5_xl_bfd) lists that it was trained with masked language modeling -- what token did you use for the masking?

Thank you!
Joshua

**Comment by agemagician** [comment]
Hi Joshua,

Thanks a lot :) 

Also, thanks to you for your awesome work and your great contribution to the bioinformatics field.

During pertaining, we have used id "127" for masking, which represents the "<extra_id_0>" token.

Just be aware that ProtT5 is an encoder-decoder model, so you can actually extract the result of the masking from either the encoder or the decoder. However, we didn't fully test that yet.

By the way, you should use "Rostlab/prot_t5_xl_uniref50" and not "Rostlab/prot_t5_xl_bfd" for better results.

Hopefully, this answers your question.

Feel free to re-open the issue or send me an email if something is not yet clear.
