### ISSUE TITLE
Do you have a plan to release the trained models for secondary structure prediction etc.?

### ISSUE THREAD

**Issue by zzhongzz** [agemagician/ProtTrans#4]
Hi,
Do you have any plan to release the fine-tuned models for protein secondary structure prediction, membrane-bound and water-soluble etc.? I think it will be very helpful if people can really use the model to predict properties of proteins.

**Comment by agemagician** [comment]
Our models were not fine-tuned to any of the downstream tasks. We only used ProtTrans models for feature extraction.

We didn't had plans to publish it, but if you think it is useful, we will add them here soon.

**Comment by darnells** [comment]
I think it would be great, especially if they also functioned as practical examples for creating new fine-tuned models using the pre-trained grammar.

**Comment by zzhongzz** [comment]
I think it will be useful to publish some of the fine-tuned models or code examples to fine-tune the model. If people can use it to reproduce the results in the "expected results" section, it will be much better.

**Comment by agemagician** [comment]
Hi @darnells @zzhongzz ,

We have published a code example using Pytorch lighting for fine-tuning ProtBert-BFD model for the Localization task.

You can find it here:
https://github.com/agemagician/ProtTrans/blob/master/Fine-Tuning/ProtBert-BFD-FineTuning-Localization.ipynb

We will try to update the fine-tuning section with more examples.

We need to mention again that in our paper we only used feature extraction method without fine-tuning.
The results on the fine-tuning section will be different from the paper (mostly better).
