### ISSUE TITLE
How to ignore the warning

### ISSUE THREAD

**Issue by SamieeS** [agemagician/ProtTrans#40]
Hi,

Thank you for your great work.
I have a quesion about how to turn off the following warning from the code, it produced 100s of messages in my log. 

Some weights of the model checkpoint at <path> were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Thank you,

**Comment by agemagician** [comment]
This warning is not harmful at all.

If you want to disable it, you have to change the warnings policy.

This link should help you:
https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

**Comment by SamieeS** [comment]
Thank you for your reply.

Yes, indeed the warning is good, but for running a long fine-tuning it just fill the log with the warning which makes the tracking difficult.
I actually tried "python -no-warning" when running and other options like "warnings.filterwarnings" in the code (before posting my origianl question), but they did not help in ignoring it. That is why I thought it may be hard-coded somewhere (not as warning).

Thank you anyways.

**Comment by andrewguy** [comment]
Hi @SamieeS ,
To suppress the warnings you can do the following:

    from transformers import logging

    logging.set_verbosity_error()
