### ISSUE TITLE
Why not use the Hugginface Hub ELECTRA?

### ISSUE THREAD

**Issue by Turakar** [agemagician/ProtTrans#43]
In your PyTorch embeddings examples, you use some custom Dropbox links to load the ELECTRA weights. However, you also published ELECTRA weights to the Huggingface Hub. Which one should I use and what is the difference?

Btw: A big thank you for publishing the weights of these resource-hungry models! :heart:

**Comment by agemagician** [comment]
Dropbox linked to: ProtElectra-Uniref100 and HuggingFace linked to: ProtElectra-BFD100.
Please, use the hugging face link because it will lead to better results.
We will update the notebook soon with the HuggingFace link.

You are welcome :)
