### ISSUE TITLE
Strange indexing for ProtT5 embeddings?

### ISSUE THREAD

**Issue by Turakar** [agemagician/ProtTrans#44]
In your ProtT5 feature extraction examples, you use the following indexing on the embeddings to obtain the sequence embedding:
```python
seq_emd = embedding[seq_num][:seq_len-1]
```
But this yields an embedding of size `seq_len - 1`, and not `seq_len`. Is this intended?

**Comment by Turakar** [comment]
This seems to be due to size of the attention mask including the additional tokens. Maybe some refactoring would be nice here. This should be equivalent to:
```python
seq_emd = embedding[seq_num][:real_seq_len]
```
Right?

**Comment by agemagician** [comment]
It is used to remove the "end of the statement" token added to each sample, as written in the note above this cell "
7. Remove padding (\<pad>) and special tokens (\</s>) that is added by ProtT5-XL-UniRef50 model".
