### ISSUE TITLE
Question about using ProtXLNet 

### ISSUE THREAD

**Issue by wafaaashraf** [agemagician/ProtTrans#47]
Hello,
First, thank you so much for your great efforts!
Second, I am aiming to use  ProtXLNet for protein variant generation. However, when I try to run the colab on the example sequence, it gives me the following error: "'NoneType' object has no attribute 'encode'" after I try to tokenized and encode the sequence example. Do you have an idea why is that?

**Comment by wafaaashraf** [comment]
the installation needs to be in the following order for the issue to be resolved: 
1. Install Transformers 
2- install SentencePiece
 3-import XLNetTokenizer 
4.create tokenizer object.

**Comment by f3n1Xx** [comment]
Thank you so much 🙏
