### ISSUE TITLE
Using ProtXLNet for Protein Variant Generation

### ISSUE THREAD

**Issue by wafaaashraf** [agemagician/ProtTrans#48]
Hello,
If I am to use ProtXLNet for variant generation (i.e., my input is entire sequences not fractions of sequence and I want to produce a variant of that sequence and not complete the sequence), is there specific recommendations for that? is ProtXLNet the best model amongst the six to begin with?

**Comment by mheinzinger** [comment]
Hey;
which model is the best will heavily depend on your specific use-case. ProtXLNet is definitely a good model to start with if I understood your use-case correctly. An alternative might be to use ProtBert's mask-fill pipeline to generate variants for a specific protein sequence: https://huggingface.co/transformers/main_classes/pipelines.html#transformers.FillMaskPipeline
You replace the amino acid at the position you want to introduce a variant by the special [MASK] token and reconstruct the most likely amino acid(s) at this position using the mask-fill pipeline linked above.
I hope this helped; good luck!
Best,
Michael
