### ISSUE TITLE
Details on T5

### ISSUE THREAD

**Issue by Turakar** [agemagician/ProtTrans#49]
First: Thank you for providing these awesome models! They help a lot with improving the predictions of my machine learning methods. :heart: 

If I understand correctly, the T5 model was not part of the original publication on biorXiv.However, it seems like this model outperforms most other LMs (it does in my studies, too). Is there a publication on this on its way? Could you provide some additional details?

**Comment by agemagician** [comment]
Hello,

I am glad that you found it useful.

Yes, T5 is our best model.  The original paper has been updated with T5 models details, you can read it from here:
https://www.biorxiv.org/content/10.1101/2020.07.12.199554v3.full.pdf

**Comment by Turakar** [comment]
Thanks
