### ISSUE TITLE
Using ProtTrans

### ISSUE THREAD

**Issue by dukkakc** [agemagician/ProtTrans#52]
Should I use a whole protein sequence or a part of a window such as 101 lengths extracted from the protein to encode with unsupervised Prot_bert. Your reply will be highly appreciated. 

How many sequences will it encode at a time? I have 29013 sequences in sequence array but it is encoding only 14507? Could you help me?

I am using the Prot_bert from the pypi,
https://pypi.org/project/bio-transformers/

from biotransformers import BioTransformers

sequences = [
        "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG",
        "KALTARQQEVFDLIRDHISQTGMPPTRAEIAQRLGFRSPNAAEEHLKALARKGVIEIVSGASRGIRLLQEE",
    ]

bio_trans = BioTransformers(backend="protbert")
embeddings = bio_trans.compute_embeddings(sequences, pool_mode=('cls','mean'),batch_size=2)

cls_emb = embeddings['cls']
mean_emb = embeddings['mean']

**Comment by dukkakc** [comment]
Is virtual amino acid such as "-" or "X" supported by Prot_bert or not.

I have 29013 sequences like this, 

sequences = [
"QKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLELLDKYLIPN",
"SGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQG",
"EILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAGEGEN------------------------------------",
]

Currently, it is encoding only 14057 sequences instead of 29013 sequences.

**Comment by agemagician** [comment]
Hello,

> Should I use a whole protein sequence or a part of a window such as 101 lengths extracted from the protein to encode with unsupervised Prot_bert. Your reply will be highly appreciated.

You should use the whole protein to extract its features.

> How many sequences will it encode at a time? I have 29013 sequences in sequence array but it is encoding only 14507? Could you help me?
> 
> I am using the Prot_bert from the pypi,
> https://pypi.org/project/bio-transformers/
> 
> from biotransformers import BioTransformers
> 
> sequences = [
> "MKTVRQERLKSIVRILERSKEPVSGAQLAEELSVSRQVIVQDIAYLRSLGYNIVATPRGYVLAGG",
> "KALTARQQEVFDLIRDHISQTGMPPTRAEIAQRLGFRSPNAAEEHLKALARKGVIEIVSGASRGIRLLQEE",
> ]
> 
> bio_trans = BioTransformers(backend="protbert")
> embeddings = bio_trans.compute_embeddings(sequences, pool_mode=('cls','mean'),batch_size=2)
> 
> cls_emb = embeddings['cls']
> mean_emb = embeddings['mean']

This is configurable and depends on your CPU or GPU memory. 
You should tweak it until you fit the maximum amount of sequences in your CPU or GPU memory.
biotransformers is a package that is not provided by us, if you want to use it, please ask its author.
Please, refer to our embedding section to use huggingface library:
https://github.com/agemagician/ProtTrans/tree/master/Embedding/PyTorch/Advanced

**Comment by agemagician** [comment]
> Is virtual amino acid such as "-" or "X" supported by Prot_bert or not.
> 
> I have 29013 sequences like this,
> 
> sequences = [
> "QKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLELLDKYLIPN",
> "SGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQG",
> "EILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAGEGEN------------------------------------",
> ]
> 
> Currently, it is encoding only 14057 sequences instead of 29013 sequences.

As you mentioned, you are using another library "BioTransformers" which was not developed by us, please refer to its author for more information.

However,  if you want to use our tested method, please refer to :
https://github.com/agemagician/ProtTrans/blob/master/Embedding/PyTorch/Advanced/ProtBert-BFD.ipynb

You have to replace rarely amino acids to "X", as mentioned on the above example:
```
sequences_Example = ["A E T C Z A O","S K T Z P"]
sequences_Example = [re.sub(r"[UZOB]", "X", sequence) for sequence in sequences_Example]
```
