### ISSUE TITLE
cuda OOM when using feature extraction

### ISSUE THREAD

**Issue by victorconan** [agemagician/ProtTrans#58]
Hi!

I am trying to use the pretrained Prot-Bert for feature extraction on some long protein sequence. I am having a NVIDIA T4 GPU with 16G memory. However, it seems the pretrained model takes a lot of memory for long protein sequence. My longest protein sequence is 5000 long, and it went OOM because it seems it will take over 15G memory to compute. 

Do you have any suggestion on how to deal with it? I extract the features to feed into another model so half precision may not be optimal for me.

Thanks!

**Comment by victorconan** [comment]
I saw in the paper, the max sequence for Prot-Bert model is 512 and 2000. I wonder if truncating the protein sequence makes sense since truncation changes the protein structure already?

**Comment by agemagician** [comment]
Hi,

Please refer to the following similar issues:
https://github.com/agemagician/ProtTrans/issues/25
https://github.com/agemagician/ProtTrans/issues/15
https://github.com/agemagician/ProtTrans/issues/55

ProtBert was trained on sequences up to 2k but it can extract features for any protein up to 40k.
