### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by CzJakethedog** [agemagician/ProtTrans#6]
Hello,

First, I would like to appreciate the hard work of your team.
And I would like to use the pretrained model for fine-tuning for my academic research project. 
However, I cannot find the link to download the pretrained model, (perhaps I overlooked?)
If it is available, could you share the link here?

Thank you

**Comment by agemagician** [comment]
Our models are fully integrated with huggingface transformers library which downloads and loads our models automatically.
You can check our repo for how to [ fine-tune ](https://github.com/agemagician/ProtTrans/tree/master/Fine-Tuning) our models or use it as a [feature extractor](https://github.com/agemagician/ProtTrans/tree/master/Embedding).

You can also download our models from the [availability section](https://github.com/agemagician/ProtTrans#models) of our repo, but we recommend to use our models through the huggingface transformers library.
