### ISSUE TITLE
Some questions of protBERT

### ISSUE THREAD

**Issue by a77564399** [agemagician/ProtTrans#62]
Hello, it is a great honor to read your ProtTrans paper, the model is very valuable to me. But I can’t understand one thing. Protbert will eventually get a 1*3*1024 vector when extracting protein features. I want to know if the second dimension(3) refers to the respective representation vector of the protein in the three-dimensional structure? Or have other meanings?

**Comment by mheinzinger** [comment]
Hi, ProtBERT returns a tensor of shape batch_size x sequence_length x embedding_dim  .
So no, the second dimension does not code for the three-dimensional structure but for the sequence length.
Feel free to confirm this by inputting a longer sequence.
