### ISSUE TITLE
Checkpoints of pre-trained models

### ISSUE THREAD

**Issue by pzhang84** [agemagician/ProtTrans#64]
The performance of protBert is impressive! I'd love to fine-tune the pre-trained bert model on my own protein sequence to see what happens. Could you point me to where can I find the checkpoints for the pre-trained models? 
It seems the pre-trained model on huggingface doesn't include checkpoint files -- https://huggingface.co/Rostlab/prot_bert/tree/main

Thanks in advance for your help!

**Comment by mheinzinger** [comment]
You are right, we focused on the PyTorch checkpoints that are available via Huggingface. I found the TF-checkpoints for ProtBERT-UniRef100 (did not find the ProtBERT-BFD checkpoints; sorry) and put them for download here: https://rostlab.org/~deepppi/protbert_u100.tar.gz

**Comment by mheinzinger** [comment]
Short addendum: I've recovered the ProtBERT-BFD TF-checkpoint and put it here for download: 
https://rostlab.org/~deepppi/protbert_bfd_tf.tar.gz
Given that ProtBERT-BFD performed better than ProtBERT-UniRef100, I would recommend to use ProtBERT-BFD for fine-tuning.
