### ISSUE TITLE
Details on Rostlab/prot_t5_base_mt_uniref50

### ISSUE THREAD

**Issue by DeepOzean** [agemagician/ProtTrans#67]
Hello,

Thank you for your excellent work, the pretrained feature extractors will help to accelerate ML on protein use cases a lot.

I have stumbled upon the "Rostlab/prot_t5_base_mt_uniref50" model. Could you provide details on it, e.g. on what dataset and task it is trained? Based on it's name, it seems to be pretrained on UniRef50, and then fine-tuned on mt=Multi-Task?

Do you think this model is suitable as a general feature extractor / for fine-tuning?

Thank you in advance for your answer.

**Comment by mheinzinger** [comment]
Thanks for your kind words and your interest in our work! :)
Regarding "Rostlab/prot_t5_base_mt_uniref50": good catch. 
Yes, this is a fine-tuned version of our ProtT5-XL-U50 model but this was highly experimental and did not work as expected. Therefor, I would generally recommend to stick to ProtT5-XL-U50 for any sort of general feature extraction: https://huggingface.co/Rostlab/prot_t5_xl_uniref50
