### ISSUE TITLE
2D t-SNE projections of single amino acids in figure 3A 

### ISSUE THREAD

**Issue by wuwo007** [agemagician/ProtTrans#69]
Thanks for sharing this great work.
Nowdays, I am studying this work. However, I encountered one problem when ploting the 2D t-SNE projections of single amino acids like the figure 3A in your paper. 
1) Which dataset did you used when ploting the figure 3A in your paper? I just saw the pre-training on BFD & UniRef50. 
2) There are multiple amino acids in one protein sequence, how do you reshape them into [20, 2]?

Looking  forward to your reply, Thanks!

**Comment by mheinzinger** [comment]
Hi, 
1.) for the single amino acid plot, we simply used a string holding the amino acids of interest. As those are uncontextualized embeddings, you do not need a sequence for this but you can just use single AAs.
2.) I guess that is also explained by 1.). The AA-plot only looks at uncontextualized token embeddings after the first embedding layer, so there is no sequence input in this specific case. So you get for each AA a vector of size 1024 which you can then project to 2D using t-SNE/Umap.
