### ISSUE TITLE
About predictprotein.org

### ISSUE THREAD

**Issue by Xinxinatg** [agemagician/ProtTrans#71]
Thanks for this pioneering work which have benefited a lot of researchers including myself! While I am tyring to use pre-trained model to predict secondary structure, the github page indicated that user shall head to predictprotein.org to input sequence. Then I found the model built within predictprotein.org is RePROF. I am wondering whether RePROF has been proved to outperform the model based on the features extracted from ProtTrans. If not how I can access the model built with features generated by ProtTrans? Looking forward to your reply.

**Comment by mheinzinger** [comment]
Hey, thanks a lot for your interest in our work.
So within [PredictProtein](https://predictprotein.org/) we've included secondary structure prediction from ProtT5. 
For backward compatibility, we've still kept the previous secondary structure predictor built in our lab (RePROF).
From our benchmarks, sec. struct. prediction from ProtT5 outperforms RePROF.
If you need to predict secondary structure for many sequences, I would recommend to use our [bio_embeddings repo](https://github.com/sacdallago/bio_embeddings) which allows you to make predictions based on ProtTrans models. Here are some [notebook examples](https://github.com/sacdallago/bio_embeddings/tree/develop/notebooks), as well as, [pipeline examples](https://github.com/sacdallago/bio_embeddings/tree/develop/examples).

**Comment by Xinxinatg** [comment]
@mheinzinger Thanks for your reply! I just checked the pipepline examples, I found that in [this page](https://github.com/sacdallago/bio_embeddings/blob/develop/examples/supervised_annotation_extraction/config.yml), only seq2vec and bert models are provided. I am wondering whether the bert means ProtBert here and **the best performing model ProtT5 trained on secondary structure/disorder dataset have been released**? I also checked in the hugging face page for [Rostlab](https://huggingface.co/Rostlab), it seems like only the ProtBert model for secondary structure prediction has been released.

**Comment by mheinzinger** [comment]
Good spot. Indeed this is the right direction. The only thing that you need to adjust now is the model that is loaded by the yaml file. In your case probably "prottrans_t5_uniref50". Here is an overview of the available models: [bio_embeddings parameters](https://github.com/sacdallago/bio_embeddings/blob/develop/examples/parameters_blueprint.yml). The models in the huggingface Rostlab repo you are referring to are fine-tuned on supervised tasks which did yield improvement in our hands. So I still recommend to use secondary structure from ProtT5.

**Comment by Xinxinatg** [comment]
@mheinzinger thanks a lot for your kind reply. I found this [document](https://docs.bioembeddings.com/develop/api/bio_embeddings.extract.html) very helpful. While trying to extract the secondary strucuture information using ProtT5 as instructed in this manual, I modified [extract_supervised_from_seqvec.ipynb](https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/extract_supervised_from_seqvec.ipynb) to generate results for ProtT5 model. However, I found the secondary structure prediction results of the particular sequence given in the [extract_supervised_from_seqvec.ipynb](https://github.com/sacdallago/bio_embeddings/blob/develop/notebooks/extract_supervised_from_seqvec.ipynb) generated by seqvec and ProtT5 are more than 50% different to each other. Would you mind kindly checking this customized [notebook](https://colab.research.google.com/drive/1n9Ta8j9cSTF-XtcXTj_5tvaiFOZzAkug?usp=sharing) for secondary structure prediction by ProtT5 to see whether I have followed the correct procedure?
