### ISSUE TITLE
what mean the word 'SS3' and 'MS'  in "ProtBert_BFD_FineTuning_MS.ipynb" or "ProtBert_BFD_FineTuning_SS3.ipynb"?

### ISSUE THREAD

**Issue by zhangzhenhuajack** [agemagician/ProtTrans#76]

**Comment by mheinzinger** [comment]
SS3 means Secondary Structure in 3-states, i.e., you are classifying each residue in a protein into one of the 3 secondary structure classes "Helix", "Sheet", "Other".
MS refers to the binary classification of a protein into "Membrane-bound" vs "Water-soluble". 
So SS3 classifies each residue in a protein while MS predicts a global property of a protein (two different levels of prediction task). 
I hope this makes it more clear. If not, feel free to re-open.
