### ISSUE TITLE
Unsupervised LM fine-tuning

### ISSUE THREAD

**Issue by fteufel** [agemagician/ProtTrans#8]
Hi, i want to do unsupervised LM fine-tuning of BERT, before training on downstream tasks.

Can I just use the utilities provided by huggingface (e.g. https://github.com/huggingface/transformers/tree/master/examples/language-modeling), starting from the checkpoint, or does anything special need to be considered?

**Comment by fteufel** [comment]
Hi, thanks for the clarification.
Just to understand the reasoning behind the newline: what modeling head did you use for pretraining? From my understanding I can instantiate the model as `BertForMaskedLM`, and then there is no next sentence classification task involved, as opposed to `BertForPreTraining`. Any reason why I should use the latter?
I'm just trying to make it work with as little changes to the code provided by huggingface as possible - in the best case just using `TFTrainer`, as I don't want to spend my time making sure my own code runs well on TPUs.

On another note:
_ProtBert was first trained for 300k steps on sequences with a maximum length of 512 and then for another 100k steps on sequences with a length of a maximum length of 2k._
Does this mean you a) removed sequences longer than 2k from the dataset, b) truncated each sequence to maximum 2k c) split sequences longer than 2k into multiple pieces and fed them to the model separately?

Thanks for the help.

**Comment by agemagician** [comment]
1.  We didn't use the transformers library for pretraining, we only used it for feature extraction and fine-tuning.
We have used the original Bert script for pretraining:
https://github.com/google-research/bert
My above comment was regarding the original TensorFlow implementation from Google.
I didn't test it, but I think "BertForMaskedLM" is the correct one that you should use for fine-tuning our Bert models for the LM task.

2. Original TensorFlow script combines two sequences per sample, i.e:
[CLS] Protein Sequence A [SEP] Protein Sequence B [SEP]
This means both sequences' length should be up to 512 or 2k.
This means on average each sequence length will be 256 or 1k.
If a sequence exceeded 256 or 1k, the rest of the tokens will be truncated.
