### ISSUE TITLE
CNN classifier for supervised learning

### ISSUE THREAD

**Issue by balvisio** [agemagician/ProtTrans#87]
Hi all,

In the paper it is explained that a CNN was chosen for the per-residue prediction. According to the paper the first layer of the CNN used a kernel of size 7 and the number of filters was 32. This layer was fed to a second Conv layer (two different CNNS: one for the 3-state and a different one for the 8-state) with kernel of size 7. I was wondering about the details of the network at this point:
- How many filters were used in this second layer?
- Was the output of this second layer flattened and run through a Dense layer to get the 3 and 8 state classification?

Thanks again!

**Comment by mheinzinger** [comment]
Hi @balvisio , 

the second layer(s) had always the number of classes that we wanted to predict as number of filters.
So we did not do any flattening etc but simply used the second CNN's layer output as class prediction.
You can find a code-example how the network looks like in this colab under Network architecture for secondary structure prediction: https://colab.research.google.com/drive/1TUj-ayG3WO52n5N50S7KH9vtt6zRkdmj?usp=sharing#scrollTo=c5XqIyeNStZP

**Comment by balvisio** [comment]
Got it. Thanks!
