### ISSUE TITLE
Using subnets of ProtTrans for protein understanding/classification tasks

### ISSUE THREAD

**Issue by xinshao-wang** [agemagician/ProtTrans#89]
First of all, many thanks to the authors of ProtTrans for releasing these amazing protein language models and code. 

Second, for those who may be interested, there is our recent work which trains subnets of ProtTrans (e.g., when GPU memory is not large enough) for robust protein understanding/classification tasks. 
[https://github.com/XinshaoAmosWang/DeepCriticalLearning#run-experiments](https://github.com/XinshaoAmosWang/DeepCriticalLearning#run-experiments). 

I am open and looking forward to feedbacks and discussions. Thanks in advance.

**Comment by mheinzinger** [comment]
Interesting, thanks for sharing! - I will try to read in more detail later (though I can not guarantee as I am busy wrapping up some other things before going on vacation).
What I already saw: maybe rather use subcellular-localization prediction together with the "Hard new test set" that we describe in the LightAttention paper for making a point on (balanced) accuracy: https://academic.oup.com/bioinformaticsadvances/article/1/1/vbab035/6432029
