### ISSUE TITLE
Add more pre-trained models for tensorflow 2

### ISSUE THREAD

**Issue by deepgradient** [agemagician/ProtTrans#9]
Hi,
Could you please kindly provide moe TensorFlow 2 pre-trained models and provide some examples fro fine-tuning task with TF 2 as well?

**Comment by agemagician** [comment]
I have added an example for loading all models using TF 2.

We currently, only provide a PyTorch example for fine-tuning tasks.
However, we will be happy to accept your pull request if you made one.

Hopefully, these answer your questions.
