### ISSUE TITLE
Generating embeddings in T5

### ISSUE THREAD

**Issue by BrahamVictor** [agemagician/ProtTrans#96]
Thanks for this magnificent work! Just wondering are there any solutions for generating sequence embeddings in real time. I found it seems the pretrained model takes a lot of memory and time for long protein sequence of length longer than ~6000.

**Comment by mheinzinger** [comment]
While we would like to provide such an online embedding-service, such an effort requires resources that we can't provide currently, unfortunately, sorry. While we think that running our pLMs is already reasonably fast for most tasks, we understand that there are problems where even more speed would be beneficial. For those problems, you could try other approaches that make existing models faster during inference/embedding-generation; an overview is given, for example, here:

https://nlpcloud.com/how-to-speed-up-deep-learning-nlp-transformers-inference.html

Alternatively, you can also download pre-computed ProtT5 embeddings of selected organisms:
https://www.uniprot.org/help/embeddings

Or use our web-service to generate predictions:
https://embed.predictprotein.org/

**Comment by BrahamVictor** [comment]
Thank you for your reply and provided sources. It would help me a lot.
