### ISSUE TITLE
Protein-protein interaction

### ISSUE THREAD

**Issue by Moeinh77** [agemagician/ProtTrans#97]
How can I perform protein-protein interaction using the models? are there any examples in the repo that I couldn't find?

**Comment by mheinzinger** [comment]
Nope you did not miss it. We have no examples on this, yet, sorry.
But there are some lines of work that might be useful as inspiration, e.g., [D-Script](https://www.sciencedirect.com/science/article/pii/S2405471221003331) or [Topsy-Turvy](https://academic.oup.com/bioinformatics/article/38/Supplement_1/i264/6617505?login=false).
But I think when you want to approach this topic, the most important part is actually not the machine learning part but the dataset preparation part, so maybe take a look at this: [More challenges for ML in PPI prediction](https://academic.oup.com/bioinformatics/article/31/10/1521/176646)

**Comment by mheinzinger** [comment]
Perfectly valid approach and def. very interesting! - If you get somewhere with this approach, it would be great if you could share your insights here :)
